/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.accountingsystem.view;

/**
 *
 * @author Lucas Gongora
 */
public class FrmAdministrator extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    public FrmAdministrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnItemConvertUnits = new javax.swing.JMenuItem();
        mnItemAddConversion = new javax.swing.JMenuItem();
        mnItemUpdateConversion = new javax.swing.JMenuItem();
        mnItemDeleteSubUnit = new javax.swing.JMenuItem();
        mnItemDeleteUnit = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        mnItemAddCustomer = new javax.swing.JMenuItem();
        mnItemUpdateCustomer = new javax.swing.JMenuItem();
        mnItemViewCustomers = new javax.swing.JMenuItem();
        mnItemDeleteCustomer = new javax.swing.JMenuItem();
        mntItemAddSupplier = new javax.swing.JMenu();
        mnItemAddSupplier = new javax.swing.JMenuItem();
        mnItemUpdateSupplier = new javax.swing.JMenuItem();
        mnItemViewSuppliers = new javax.swing.JMenuItem();
        mnItemDeleteSupplier = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        jMenu9.setText("jMenu9");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas\\Desktop\\Carrera\\segundo-tercer-semestre\\POO\\proyecto\\ESPE2410-OOPSW1973-NightmareSquad\\06-Code\\GUI\\AccountingSystem\\src\\main\\java\\images\\logo.jpg")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setText("StockBill");

        jMenu1.setText("Billing");

        jMenu11.setText("Sale");
        jMenu1.add(jMenu11);

        jMenu12.setText("Purchase");
        jMenu1.add(jMenu12);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventory");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transactions");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Conversión");

        mnItemConvertUnits.setText("Convertir unidades");
        mnItemConvertUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemConvertUnitsActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemConvertUnits);

        mnItemAddConversion.setText("Añadir");
        mnItemAddConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAddConversionActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemAddConversion);

        mnItemUpdateConversion.setText("Actualizar");
        mnItemUpdateConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemUpdateConversionActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemUpdateConversion);

        mnItemDeleteSubUnit.setText("Eliminar valor de conversión");
        mnItemDeleteSubUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteSubUnitActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemDeleteSubUnit);

        mnItemDeleteUnit.setText("Eliminar conversiones de una unidad");
        mnItemDeleteUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteUnitActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemDeleteUnit);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Branches");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Vouchers");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Cliente");

        mnItemAddCustomer.setText("Añadir");
        mnItemAddCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemAddCustomerMouseClicked(evt);
            }
        });
        mnItemAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAddCustomerActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemAddCustomer);

        mnItemUpdateCustomer.setText("Actualizar");
        mnItemUpdateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemUpdateCustomerMouseClicked(evt);
            }
        });
        mnItemUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemUpdateCustomerActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemUpdateCustomer);

        mnItemViewCustomers.setText("Mostrar");
        mnItemViewCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemViewCustomersMouseClicked(evt);
            }
        });
        mnItemViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemViewCustomersActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemViewCustomers);

        mnItemDeleteCustomer.setText("Eliminar");
        mnItemDeleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemDeleteCustomerMouseClicked(evt);
            }
        });
        mnItemDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteCustomerActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemDeleteCustomer);

        jMenuBar1.add(jMenu7);

        mntItemAddSupplier.setText("Proveedor");

        mnItemAddSupplier.setText("Añadir");
        mnItemAddSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemAddSupplierMouseClicked(evt);
            }
        });
        mnItemAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAddSupplierActionPerformed(evt);
            }
        });
        mntItemAddSupplier.add(mnItemAddSupplier);

        mnItemUpdateSupplier.setText("Actualizar");
        mnItemUpdateSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemUpdateSupplierMouseClicked(evt);
            }
        });
        mnItemUpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemUpdateSupplierActionPerformed(evt);
            }
        });
        mntItemAddSupplier.add(mnItemUpdateSupplier);

        mnItemViewSuppliers.setText("Mostrar");
        mnItemViewSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemViewSuppliersMouseClicked(evt);
            }
        });
        mnItemViewSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemViewSuppliersActionPerformed(evt);
            }
        });
        mntItemAddSupplier.add(mnItemViewSuppliers);

        mnItemDeleteSupplier.setText("Eliminar");
        mnItemDeleteSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemDeleteSupplierMouseClicked(evt);
            }
        });
        mnItemDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteSupplierActionPerformed(evt);
            }
        });
        mntItemAddSupplier.add(mnItemDeleteSupplier);

        jMenuBar1.add(mntItemAddSupplier);

        jMenu10.setText("Exit");
        jMenu10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu10MouseClicked

    private void mnItemAddCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemAddCustomerMouseClicked

    }//GEN-LAST:event_mnItemAddCustomerMouseClicked

    private void mnItemUpdateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemUpdateCustomerMouseClicked

    }//GEN-LAST:event_mnItemUpdateCustomerMouseClicked

    private void mnItemViewCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemViewCustomersMouseClicked


    }//GEN-LAST:event_mnItemViewCustomersMouseClicked

    private void mnItemDeleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemDeleteCustomerMouseClicked


    }//GEN-LAST:event_mnItemDeleteCustomerMouseClicked

    private void mnItemAddSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemAddSupplierMouseClicked

    }//GEN-LAST:event_mnItemAddSupplierMouseClicked

    private void mnItemUpdateSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemUpdateSupplierMouseClicked

    }//GEN-LAST:event_mnItemUpdateSupplierMouseClicked

    private void mnItemViewSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemViewSuppliersMouseClicked

    }//GEN-LAST:event_mnItemViewSuppliersMouseClicked

    private void mnItemDeleteSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemDeleteSupplierMouseClicked

    }//GEN-LAST:event_mnItemDeleteSupplierMouseClicked

    private void mnItemAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAddCustomerActionPerformed
        FrmCustomerAddition frmCustomerAddition = new FrmCustomerAddition();
        frmCustomerAddition.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemAddCustomerActionPerformed

    private void mnItemUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemUpdateCustomerActionPerformed
        FrmCustomerUpdating frmCustomerUpdating = new FrmCustomerUpdating();
        frmCustomerUpdating.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemUpdateCustomerActionPerformed

    private void mnItemViewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemViewCustomersActionPerformed
        System.out.println("Holaaaaa");
        FrmCustomerView frmCustomerView = new FrmCustomerView();
        frmCustomerView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemViewCustomersActionPerformed

    private void mnItemDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteCustomerActionPerformed
        FrmCustomerElimination frmCustomerElimination = new FrmCustomerElimination();
        frmCustomerElimination.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemDeleteCustomerActionPerformed

    private void mnItemAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAddSupplierActionPerformed
        FrmSupplierAddition frmSupplierAddition = new FrmSupplierAddition();
        frmSupplierAddition.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemAddSupplierActionPerformed

    private void mnItemUpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemUpdateSupplierActionPerformed
        FrmSupplierUpdating frmSupplierUpdating = new FrmSupplierUpdating();
        frmSupplierUpdating.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemUpdateSupplierActionPerformed

    private void mnItemViewSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemViewSuppliersActionPerformed
        FrmSuppliersView frmSuppliersView = new FrmSuppliersView();
        frmSuppliersView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemViewSuppliersActionPerformed

    private void mnItemDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteSupplierActionPerformed
        FrmSupplierElimination frmSupplierElimination = new FrmSupplierElimination();
        frmSupplierElimination.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemDeleteSupplierActionPerformed

    private void mnItemUpdateConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemUpdateConversionActionPerformed
        FrmConversionUpdating frmConversionUpdating = new FrmConversionUpdating();
        frmConversionUpdating.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemUpdateConversionActionPerformed

    private void mnItemAddConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAddConversionActionPerformed
        FrmConversionAddition frmConversionAddition = new FrmConversionAddition();
        frmConversionAddition.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemAddConversionActionPerformed

    private void mnItemConvertUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemConvertUnitsActionPerformed
        FrmConverterUnits frmConverterUnits = new FrmConverterUnits();
        frmConverterUnits.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemConvertUnitsActionPerformed

    private void mnItemDeleteSubUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteSubUnitActionPerformed
        FrmFinalUnitElimination frmFinalUnitElimination = new FrmFinalUnitElimination();
        frmFinalUnitElimination.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mnItemDeleteSubUnitActionPerformed

    private void mnItemDeleteUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteUnitActionPerformed
       FrmSourceUnitElimination frmSourceUnitElimination;
       frmSourceUnitElimination = new FrmSourceUnitElimination();
       frmSourceUnitElimination.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_mnItemDeleteUnitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mnItemAddConversion;
    private javax.swing.JMenuItem mnItemAddCustomer;
    private javax.swing.JMenuItem mnItemAddSupplier;
    private javax.swing.JMenuItem mnItemConvertUnits;
    private javax.swing.JMenuItem mnItemDeleteCustomer;
    private javax.swing.JMenuItem mnItemDeleteSubUnit;
    private javax.swing.JMenuItem mnItemDeleteSupplier;
    private javax.swing.JMenuItem mnItemDeleteUnit;
    private javax.swing.JMenuItem mnItemUpdateConversion;
    private javax.swing.JMenuItem mnItemUpdateCustomer;
    private javax.swing.JMenuItem mnItemUpdateSupplier;
    private javax.swing.JMenuItem mnItemViewCustomers;
    private javax.swing.JMenuItem mnItemViewSuppliers;
    private javax.swing.JMenu mntItemAddSupplier;
    // End of variables declaration//GEN-END:variables
}
