
package ec.edu.espe.accountingsystem.view;

<<<<<<< HEAD
import ec.edu.espe.accountingsystem.controller.SupplierController;
import ec.edu.espe.accountingsystem.controller.UserController;
import ec.edu.espe.accountingsystem.exception.InvalidIdentityCardException;
import ec.edu.espe.accountingsystem.model.Supplier;
=======
import ec.edu.espe.accountingsystem.exception.InvalidIdentityCardException;
import ec.edu.espe.accountingsystem.model.IdentityCard;
import ec.edu.espe.accountingsystem.model.Supplier;
import ec.edu.espe.accountingsystem.model.SuppliersRecord;
import java.util.logging.Level;
import java.util.logging.Logger;
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Espinosa
 */
public class FrmSupplierUpdating extends javax.swing.JFrame {
    
        String id;
        String name;
        IdentityCard identityCard;
        String identityCardType;
        String identityCardId;
        String address;
        String phoneNumber;
        String email;

    SupplierController supplierController;
    UserController userController;

    /**
     * Creates new form SupplierUpdating
     */
    public FrmSupplierUpdating() {
        initComponents();
<<<<<<< HEAD
        supplierController = new SupplierController();
        userController = new UserController();
=======
        lblIdVoidField.setVisible(false);
        lblNameVoidField.setVisible(false);
        lblIdentityCardTypeVoidField.setVisible(false);
        lblIdentityCardIdVoidField.setVisible(false);
        lblAddressVoidField.setVisible(false);
        lblPhoneNumberVoidField.setVisible(false);
        lblEmailVoidField.setVisible(false);
        
        labelName.setVisible(false);
        txtName.setVisible(false);
        labelIdentityCardType.setVisible(false);
        txtIdentityCardType.setVisible(false);
        labelIdentityCardId.setVisible(false);
        txtIdentityCardId.setVisible(false);
        labelAddress.setVisible(false);
        txtAddress.setVisible(false);
        labelPhoneNumber.setVisible(false);
        txtPhoneNumber.setVisible(false);
        labelEmail.setVisible(false);
        txtEmail.setVisible(false);
        btnUpdateChanges.setVisible(false);
        btnBacktoMenu.setVisible(false);
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelEditASupplier = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelInserId = new javax.swing.JLabel();
        txtInsertId = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelIdentityCardType = new javax.swing.JLabel();
        labelIdentityCardId = new javax.swing.JLabel();
<<<<<<< HEAD
        labelAdress = new javax.swing.JLabel();
        labelPhoneNumber = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbxIdentityCardType = new javax.swing.JComboBox<>();
=======
        labelAddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtIdentityCardType = new javax.swing.JTextField();
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
        txtIdentityCardId = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
<<<<<<< HEAD
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelEditASupplier.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelEditASupplier.setText("Actualizar Proveedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(labelEditASupplier)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(labelEditASupplier)
                .addGap(35, 35, 35))
        );

        labelInserId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelInserId.setText("Ingresa el id del cliente que quieres actualizar");

        txtInsertId.addActionListener(new java.awt.event.ActionListener() {
=======
        labelEmail = new javax.swing.JLabel();
        btnUpdateChanges = new javax.swing.JButton();
        btnBacktoMenu = new javax.swing.JButton();
        lblIdVoidField = new javax.swing.JLabel();
        lblNameVoidField = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        lblIdentityCardTypeVoidField = new javax.swing.JLabel();
        lblIdentityCardIdVoidField = new javax.swing.JLabel();
        lblAddressVoidField = new javax.swing.JLabel();
        lblPhoneNumberVoidField = new javax.swing.JLabel();
        lblEmailVoidField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelEditASupplier.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEditASupplier.setText("Actualizar un Proveedor");

        labelInserId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelInserId.setText("Ingrese el ID del proveedor que desea actualizar");

        labelName.setText("Nombre:");

        labelIdentityCardType.setText("Tipo de tarjeta de identificación:");

        labelIdentityCardId.setText("ID de la tarjeta de identificación:");

        labelAddress.setText("Dirección:");

        txtIdentityCardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentityCardTypeActionPerformed(evt);
            }
        });

        labelPhoneNumber.setText("Número de Telefono:");

        labelEmail.setText("Email");

        btnUpdateChanges.setBackground(new java.awt.Color(34, 51, 186));
        btnUpdateChanges.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateChanges.setText("Actualizar Cambios");
        btnUpdateChanges.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertIdActionPerformed(evt);
            }
        });
        txtInsertId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInsertIdKeyTyped(evt);
            }
        });

<<<<<<< HEAD
        labelName.setText("Nombre:");

        labelIdentityCardName.setText("Tipo de documento de identidad:");

        labelIdentityCardId.setText("Número de documento de identidad");

        labelAdress.setText("Dirección:");

        labelPhoneNumber.setText("Número de teléfono:");

        labelEmail.setText("Correo electrónico:");

        txtName.setEnabled(false);

        cmbxIdentityCardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cedula", "ruc" }));
        cmbxIdentityCardType.setEnabled(false);
        cmbxIdentityCardType.addActionListener(new java.awt.event.ActionListener() {
=======
        btnBacktoMenu.setBackground(new java.awt.Color(34, 51, 186));
        btnBacktoMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnBacktoMenu.setText("Regresar al Menú");
        btnBacktoMenu.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxIdentityCardTypeActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        txtIdentityCardId.setEnabled(false);

        txtAdress.setEnabled(false);

        txtPhoneNumber.setEnabled(false);

        txtEmail.setEnabled(false);

        btnUpdate.setBackground(new java.awt.Color(34, 51, 186));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Actualizar");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setText("Teclea ENTER para ver datos del proveedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInserId)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtInsertId, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(labelIdentityCardName)
                            .addComponent(labelIdentityCardId)
                            .addComponent(labelAdress)
                            .addComponent(labelPhoneNumber)
                            .addComponent(labelEmail))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbxIdentityCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtIdentityCardId)
                            .addComponent(txtAdress)
                            .addComponent(txtPhoneNumber)
                            .addComponent(txtEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInserId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentityCardName)
                    .addComponent(cmbxIdentityCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentityCardId)
                    .addComponent(txtIdentityCardId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdress)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("Regresar al menu principal");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
=======
        lblIdVoidField.setForeground(new java.awt.Color(255, 51, 51));
        lblIdVoidField.setText("* Cambo Vacío");

        lblNameVoidField.setForeground(new java.awt.Color(255, 51, 51));
        lblNameVoidField.setText("* Campo Vacío");

        btnFind.setBackground(new java.awt.Color(34, 51, 186));
        btnFind.setForeground(new java.awt.Color(255, 255, 255));
        btnFind.setText("Encontrar");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        lblIdentityCardTypeVoidField.setForeground(new java.awt.Color(255, 51, 51));
        lblIdentityCardTypeVoidField.setText("* Campo Vacío");

        lblIdentityCardIdVoidField.setForeground(new java.awt.Color(255, 51, 51));
        lblIdentityCardIdVoidField.setText("* Campo Vacío");

        lblAddressVoidField.setForeground(new java.awt.Color(255, 51, 51));
        lblAddressVoidField.setText("* Campo Vacío");

        lblPhoneNumberVoidField.setForeground(new java.awt.Color(255, 51, 51));
        lblPhoneNumberVoidField.setText("* Campo Vacío");

        lblEmailVoidField.setForeground(new java.awt.Color(255, 51, 51));
        lblEmailVoidField.setText("* Campo Vacío");
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
=======
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEditASupplier)
                .addGap(200, 200, 200))
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
=======
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInserId, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInsertId, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFind)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIdVoidField)
                                        .addComponent(labelAddress))
                                    .addGap(103, 103, 103)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAddress)
                                        .addComponent(txtName)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNameVoidField)
                                                .addComponent(lblIdentityCardTypeVoidField)
                                                .addComponent(lblIdentityCardIdVoidField))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelIdentityCardType)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtIdentityCardType))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelPhoneNumber)
                                        .addComponent(labelEmail))
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmailVoidField)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPhoneNumber)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblAddressVoidField)
                                                    .addComponent(lblPhoneNumberVoidField))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtEmail))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnUpdateChanges)
                                        .addComponent(labelIdentityCardId))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(297, 297, 297)
                                            .addComponent(btnBacktoMenu))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIdentityCardId, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(labelName))
                        .addContainerGap(16, Short.MAX_VALUE))))
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addGap(10, 10, 10)
                .addComponent(labelEditASupplier)
                .addGap(18, 18, 18)
                .addComponent(labelInserId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(2, 2, 2)
                .addComponent(lblIdVoidField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNameVoidField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentityCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentityCardType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdentityCardTypeVoidField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentityCardId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentityCardId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdentityCardIdVoidField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAddress))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelPhoneNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddressVoidField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumberVoidField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmailVoidField)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBacktoMenu)
                    .addComponent(btnUpdateChanges))
                .addGap(18, 18, 18))
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String id;
        String name;
        String identityCardType;
        String identityCardNumber;
        String address;
        String phoneNumber;
        String email;
        boolean isValid;
        Supplier supplier;

        id = txtInsertId.getText();
        name = txtName.getText();
        identityCardType = cmbxIdentityCardType.getSelectedItem().toString();
        identityCardNumber = txtIdentityCardId.getText();
        address = txtAdress.getText();
        phoneNumber = txtPhoneNumber.getText();
        email = txtEmail.getText();
        supplier = supplierController.getSupplier(id);
        if (supplier != null) {
            try {
                isValid = supplierController.update(id, name, identityCardType, identityCardNumber, address, phoneNumber, email);
                if (isValid) {
                    JOptionPane.showMessageDialog(rootPane, "Actualizado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se pudo actualizar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (InvalidIdentityCardException ex) {
                JOptionPane.showMessageDialog(rootPane, "No se pudo actualizar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "ID inválido", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cmbxIdentityCardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxIdentityCardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxIdentityCardTypeActionPerformed

    private void txtInsertIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertIdActionPerformed
        String id = txtInsertId.getText().trim();
        updateFields(id);

    }//GEN-LAST:event_txtInsertIdActionPerformed

    private void txtInsertIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsertIdKeyTyped

    }//GEN-LAST:event_txtInsertIdKeyTyped

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        if(userController.isAdministrator()){
            FrmAdministrator frmAdministrator = new FrmAdministrator();
            frmAdministrator.setVisible(true);
        }else{
            FrmSeller frmSeller = new FrmSeller();
            frmSeller.setVisible(true);
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void updateFields(String id) {
        if (id == null || id.trim().isEmpty()) {
            txtName.setText("");
            txtIdentityCardId.setText("");
            cmbxIdentityCardType.setSelectedItem("");
            txtAdress.setText("");
            txtPhoneNumber.setText("");
            txtEmail.setText("");

            txtName.setEnabled(false);
            txtIdentityCardId.setEnabled(false);
            cmbxIdentityCardType.setEnabled(false);
            txtAdress.setEnabled(false);
            txtPhoneNumber.setEnabled(false);
            txtEmail.setEnabled(false);
            btnUpdate.setEnabled(false);
        } else {
            Supplier supplier = supplierController.getSupplier(id);

            if (supplier != null) {
                String name = supplier.getName();
                String identityCardNumber = supplier.getIdentityCard().getId();
                String identityCardType = supplier.getIdentityCard().getType();
                String address = supplier.getAddress();
                String phoneNumber = supplier.getPhoneNumber();
                String email = supplier.getEmail();

                txtName.setText(name);
                txtIdentityCardId.setText(identityCardNumber);
                cmbxIdentityCardType.setSelectedItem(identityCardType);
                txtAdress.setText(address);
                txtPhoneNumber.setText(phoneNumber);
                txtEmail.setText(email);

                txtName.setEnabled(true);
                txtIdentityCardId.setEnabled(true);
                cmbxIdentityCardType.setEnabled(true);
                txtAdress.setEnabled(true);
                txtPhoneNumber.setEnabled(true);
                txtEmail.setEnabled(true);
                btnUpdate.setEnabled(true);
            } else {
                txtName.setText("");
                txtIdentityCardId.setText("");
                cmbxIdentityCardType.setSelectedItem("");
                txtAdress.setText("");
                txtPhoneNumber.setText("");
                txtEmail.setText("");

                txtName.setEnabled(false);
                txtIdentityCardId.setEnabled(false);
                cmbxIdentityCardType.setEnabled(false);
                txtAdress.setEnabled(false);
                txtPhoneNumber.setEnabled(false);
                txtEmail.setEnabled(false);
                btnUpdate.setEnabled(false);
            }
        }
    }
=======
    private void btnUpdateChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateChangesActionPerformed
        
        boolean validatedData;
        
        
        if(txtName.getText().trim().isEmpty()){
            
            lblNameVoidField.setVisible(true);
            validatedData = false;
        }else{
            lblNameVoidField.setVisible(false);
            name = txtName.getText();
            validatedData = true;
        }
        
        if(txtIdentityCardType.getText().trim().isEmpty()){
            
            lblIdentityCardTypeVoidField.setVisible(true);
            validatedData = false;
        }else{
            lblIdentityCardTypeVoidField.setVisible(false);
            identityCardType = txtIdentityCardType.getText();
            validatedData = true;
        }
        
        if(txtIdentityCardId.getText().trim().isEmpty()){
            
            lblIdentityCardIdVoidField.setVisible(true);
            validatedData = false;
        }else{
            lblIdentityCardIdVoidField.setVisible(false);
            identityCardId = txtIdentityCardId.getText();
            validatedData = true;
        }
        
        
            try {
                identityCard = new IdentityCard(identityCardType, identityCardId);
                validatedData = true;
            } catch (InvalidIdentityCardException ex) {
                Logger.getLogger(FrmSupplierAddition.class.getName()).log(Level.SEVERE, null, ex);
                validatedData = false;
            }
            
        if(txtAddress.getText().trim().isEmpty()){
            
            lblAddressVoidField.setVisible(true);
            validatedData = false;
        }else{
            lblAddressVoidField.setVisible(false);
            address = txtAddress.getText();
            validatedData = true;
        }
        
        if(txtPhoneNumber.getText().trim().isEmpty()){
            
            lblPhoneNumberVoidField.setVisible(true);
            validatedData = false;
        }else{
            lblPhoneNumberVoidField.setVisible(false);
            phoneNumber = txtPhoneNumber.getText();
            validatedData = true;
        }
        
        if(txtEmail.getText().trim().isEmpty()){
            
            lblEmailVoidField.setVisible(true);
            validatedData = false;
        }else{
            lblEmailVoidField.setVisible(false);
            email = txtEmail.getText();
            validatedData = true;
        }
        
        if(validatedData==true){
            Supplier supplier = new Supplier(id, name, identityCard, address, phoneNumber, email);

            SuppliersRecord suppliers = new SuppliersRecord();

            suppliers.add(supplier);
            
            JOptionPane.showMessageDialog(rootPane, "Se han actualizado los datos correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            txtName.setText("");
            txtIdentityCardType.setText("");
            txtIdentityCardId.setText("");
            txtAddress.setText("");
            txtPhoneNumber.setText("");
            txtEmail.setText("");
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Campos no llenados correctamente", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateChangesActionPerformed

    private void btnBacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoMenuActionPerformed
        FrmAdministrator administratorWindow = new FrmAdministrator();
        administratorWindow.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBacktoMenuActionPerformed
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b

    private void txtIdentityCardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentityCardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentityCardTypeActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        
        Supplier supplier;
        SuppliersRecord suppliers = new SuppliersRecord();
        if(txtInsertId.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campos no llenados correctamente", "Error", JOptionPane.WARNING_MESSAGE);
            lblIdVoidField.setVisible(true);
        }else{
            lblIdVoidField.setVisible(false);
            id = txtInsertId.getText();
        }
        
        if(suppliers.findSupplierById(id)!=null){
            supplier = suppliers.findSupplierById(id);
            labelName.setVisible(true);
            txtName.setVisible(true);
            txtName.setText(supplier.getName());
            
            labelIdentityCardType.setVisible(true);
            txtIdentityCardType.setVisible(true);
            txtIdentityCardType.setText(supplier.getIdentityCard().getType());
            
            labelIdentityCardId.setVisible(true);
            txtIdentityCardId.setVisible(true);
            txtIdentityCardId.setText(supplier.getIdentityCard().getId());
            
            labelAddress.setVisible(true);
            txtAddress.setVisible(true);
            txtAddress.setText(supplier.getAddress());
            
            labelPhoneNumber.setVisible(true);
            txtPhoneNumber.setVisible(true);
            txtPhoneNumber.setText(supplier.getPhoneNumber());
            
            labelEmail.setVisible(true);
            txtEmail.setVisible(true);
            txtEmail.setText(supplier.getEmail());
            
            btnUpdateChanges.setVisible(true);
            
            btnBacktoMenu.setVisible(true);
        
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "No existe ningún proveedor con la ID ingresada", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSupplierUpdating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSupplierUpdating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSupplierUpdating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSupplierUpdating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSupplierUpdating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbxIdentityCardType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAdress;
=======
    private javax.swing.JButton btnBacktoMenu;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdateChanges;
    private javax.swing.JLabel labelAddress;
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
    private javax.swing.JLabel labelEditASupplier;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelIdentityCardId;
    private javax.swing.JLabel labelIdentityCardType;
    private javax.swing.JLabel labelInserId;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhoneNumber;
    private javax.swing.JLabel lblAddressVoidField;
    private javax.swing.JLabel lblEmailVoidField;
    private javax.swing.JLabel lblIdVoidField;
    private javax.swing.JLabel lblIdentityCardIdVoidField;
    private javax.swing.JLabel lblIdentityCardTypeVoidField;
    private javax.swing.JLabel lblNameVoidField;
    private javax.swing.JLabel lblPhoneNumberVoidField;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdentityCardId;
<<<<<<< HEAD
=======
    private javax.swing.JTextField txtIdentityCardType;
>>>>>>> 322cd0604aec6bda80e3c93b9c15319539c9717b
    private javax.swing.JTextField txtInsertId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
